### ISSUE TITLE
some articles appears without pictures - see attached

### ISSUE THREAD

**Issue by fridabu** [WebAhead5/Coronews#34]
![coronnewsNoPictures](https://user-images.githubusercontent.com/4709824/77628408-aedce380-6f50-11ea-9775-53266474d0bf.png)

**Comment by jrd656** [comment]
This is where the API doesn't provide them. We'll discuss and decide if we want to include a default image, but I think it's possibly fine as it is :-)

**Comment by MorisR** [comment]
resolved  96b82b348710efdfb1506a3b20680c5ae10da2dc
